### ISSUE TITLE
COIs color and width to improve image export quality

### ISSUE THREAD

**Issue by matfallet** [elodiegermani/SAPHIR#3]
Dear Elodie,
Could you change the default color and the line width (too thin) of COIs in the plot to image menu.
If we want to export the image with  COIs in link to the scatterplot for publication, it will be great to have the possibility to choose the COIs color depending of the color of the image behind. We need to export  two gates in the scatterplot  corresponding to two cells populations. The choice of color could be (white, yellow, green, red, blue, cyan, magenta).
Thanks very much.

Mathieu

**Comment by matfallet** [comment]
Maybe the first improvement could be to change the default color in b&w when using no overlay (one channels).  If the default color of the COIs is yellow, it should be quite visible ?

**Comment by elodiegermani** [comment]
Dear Mathieu, 
I released a new version of SAPHIR with two new options :
- possibility to change the colors in which the selections on the plot are displayed on the image (Menu Plot to Image) : top right corner, below the legend table, you can choose to modify these legends by clicking on the button : radiobuttons will appear, you will have to select the colors you want for each selection type (quadrants in the plot or selection number if multiple selection) and "Apply" when you are satisfied with the colors. 
- possibility to increase the thickness of COI's highlight on images (Menu Plot to Image, Image to Plot and Annotation) : checkbox button to check and slider to choose the desired thickness. 
Best regards, 
Elodie
